version: 2.1
executors:
  docker-executor:
    docker:
      - image: nginx:latest
      - image: docker:20.10.8
     

jobs:
  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build -t arjit547/circleci .
            echo $DOCKER_PASSWORD | docker login -u arjit547 --password-stdin
            docker push arjit547/circleci

workflows:
  build_test:
    jobs:
      - build_docker_image
